# Generated by Django 4.2.18 on 2025-04-14 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('BP0', 'BPO'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
